import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/landing',
          '/home-feed',
          '/short-videos',
          '/video-live-feed',
          '/search-engine',
          '/marketplace',
          '/ecommerce',
          '/ai-assistant',
          '/hn-ai',
          '/voice-rooms',
          '/games-hub',
          '/crypto-trading',
          '/pages-groups',
          '/geo-content',
          '/invite',
          '/sign-up-login',
          '/subscription',
          '/live-stream',
          '/stories-editor',
          '/app-store',
          '/profile',
          '/privacy-policy',
          '/terms-of-service',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/owner',
          '/owner/',
          '/owner-login',
          '/api/',
          '/user-settings',
          '/preferences',
          '/onboarding',
          '/monitoring',
          '/email-dashboard',
          '/growth-analytics',
          '/push-strategy',
          '/ads-manager',
          '/ads-promo',
          '/checkout',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: ['/admin/', '/owner/', '/api/'],
      },
      {
        userAgent: 'GPTBot',
        allow: ['/landing', '/sign-up-login', '/privacy-policy', '/terms-of-service'],
        disallow: ['/admin/', '/owner/', '/api/'],
      },
      {
        userAgent: 'ClaudeBot',
        allow: ['/landing', '/sign-up-login', '/privacy-policy', '/terms-of-service'],
        disallow: ['/admin/', '/owner/', '/api/'],
      },
      {
        userAgent: 'PerplexityBot',
        allow: ['/landing', '/sign-up-login', '/privacy-policy', '/terms-of-service'],
        disallow: ['/admin/', '/owner/', '/api/'],
      },
    ],
    sitemap: 'https://hnchat.net/sitemap.xml',
    host: 'https://hnchat.net',
  };
}
